# Generated by Django 5.2.4 on 2025-12-14 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRiskFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("low", "Low"), ("med", "Medium"), ("high", "High")], max_length=8
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fraud", "Fraud"),
                            ("abuse", "Abuse"),
                            ("chargeback", "Chargeback"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_flags_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "active"], name="operator_us_user_id_bc3100_idx"),
                    models.Index(
                        fields=["category", "active"], name="operator_us_categor_a30102_idx"
                    ),
                    models.Index(fields=["created_at"], name="operator_us_created_6e6eac_idx"),
                ],
            },
        ),
    ]
