# Generated by Django 5.2.7 on 2025-11-15 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0005_category_accent_category_icon_category_icon_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(help_text="End date (checkout), must be after start_date."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "requested"),
                            ("confirmed", "confirmed"),
                            ("canceled", "canceled"),
                            ("completed", "completed"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("deposit_hold_id", models.CharField(blank=True, default="", max_length=120)),
                ("totals", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="listings.listing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_renter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "start_date", "end_date"],
                        name="bookings_bo_listing_437bd0_idx",
                    ),
                    models.Index(
                        fields=["renter", "status"], name="bookings_bo_renter__03bef2_idx"
                    ),
                    models.Index(fields=["owner", "status"], name="bookings_bo_owner_i_0db98f_idx"),
                ],
            },
        ),
    ]
