# Generated by Django 5.2.7 on 2025-11-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_charge_payment_intent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "requested"),
                    ("confirmed", "confirmed"),
                    ("paid", "paid"),
                    ("canceled", "canceled"),
                    ("completed", "completed"),
                ],
                default="requested",
                max_length=16,
            ),
        ),
    ]
