# Generated by Django 5.2.7 on 2025-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="auto_canceled",
            field=models.BooleanField(
                default=False,
                help_text="True if the booking was canceled automatically by the system.",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="before_photos_required",
            field=models.BooleanField(
                default=True,
                help_text="If True, renter must upload 'before' photos before pickup confirmation.",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="before_photos_uploaded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When renter finished uploading 'before' photos for this booking.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="canceled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("renter", "renter"),
                    ("owner", "owner"),
                    ("system", "system"),
                    ("no_show", "no_show"),
                ],
                help_text="Who initiated the cancellation, if any.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="canceled_reason",
            field=models.CharField(
                blank=True,
                help_text="Optional free-text description of why the booking was canceled.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_confirmed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when owner confirmed pickup.", null=True
            ),
        ),
    ]
