# Generated by Django 5.2.7 on 2025-11-19 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_auto_canceled_booking_before_photos_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("before", "before"), ("after", "after")], default="before", max_length=16)),
                ("s3_key", models.CharField(max_length=512)),
                ("url", models.URLField(blank=True, max_length=1024)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("etag", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("pending", "pending"), ("active", "active"), ("blocked", "blocked")], default="pending", max_length=12)),
                ("av_status", models.CharField(choices=[("pending", "pending"), ("clean", "clean"), ("infected", "infected"), ("error", "error")], default="pending", max_length=12)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.ForeignKey(on_delete=models.CASCADE, related_name="photos", to="bookings.booking")),
                ("uploaded_by", models.ForeignKey(on_delete=models.CASCADE, related_name="booking_photos", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
