# Generated by Django 5.2.7 on 2025-11-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_conversation_message"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="Message"),
                migrations.DeleteModel(name="Conversation"),
            ],
        )
    ]
