# Generated by Django 5.2.4 on 2025-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_move_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='after_photos_uploaded_at',
            field=models.DateTimeField(blank=True, help_text="When renter completed uploading 'after' photos.", null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_release_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When a damage deposit release was scheduled.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_released_at',
            field=models.DateTimeField(blank=True, help_text='When the damage deposit hold was actually released.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_window_expires_at',
            field=models.DateTimeField(blank=True, help_text='End of the post-return dispute window.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When owner confirmed the tool return.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='returned_by_renter_at',
            field=models.DateTimeField(blank=True, help_text='When renter indicated the tool has been returned.', null=True),
        ),
    ]
