# Generated by Django 5.2.4 on 2025-12-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_after_photos_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_locked',
            field=models.BooleanField(default=False, help_text='When True, automatic deposit release is blocked while a dispute is active.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_disputed',
            field=models.BooleanField(default=False, help_text='True when at least one dispute case is open for this booking.'),
        ),
    ]
