# Generated by Django 5.2.4 on 2026-01-08 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_booking_deposit_authorization_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookingphoto",
            index=models.Index(fields=["booking", "role"], name="bookings_bo_booking_ee69b2_idx"),
        ),
    ]
