# Generated by Django 5.2.7 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_bookingphoto_bookings_bo_booking_ee69b2_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the booking charge succeeded and the booking became paid.",
                null=True,
            ),
        ),
    ]
