# Generated by Django 5.2.7 on 2026-01-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_booking_paid_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="owner_statement_s3_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 key for the owner earnings statement PDF.",
                max_length=255,
            ),
        ),
    ]
