# Generated by Django 5.2.4 on 2025-12-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationlog",
            old_name="notification_created_65a70b_idx",
            new_name="notificatio_created_01830a_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            old_name="notification_booking_7d8d32_idx",
            new_name="notificatio_booking_4e27c3_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            old_name="notification_type_cre_136b3c_idx",
            new_name="notificatio_type_17fc89_idx",
        ),
    ]

