# Generated by Django 5.2.7 on 2025-11-20

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0006_conversation_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Conversation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("is_active", models.BooleanField(default=True)),
                        (
                            "created_at",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        (
                            "booking",
                            models.OneToOneField(
                                on_delete=models.CASCADE,
                                related_name="conversation",
                                to="bookings.booking",
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                on_delete=models.CASCADE,
                                related_name="owner_conversations",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "renter",
                            models.ForeignKey(
                                on_delete=models.CASCADE,
                                related_name="renter_conversations",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-created_at"],
                        "db_table": "bookings_conversation",
                    },
                ),
                migrations.CreateModel(
                    name="Message",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "message_type",
                            models.CharField(
                                choices=[("user", "User"), ("system", "System")],
                                default="user",
                                max_length=10,
                            ),
                        ),
                        (
                            "system_kind",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("REQUEST_SENT", "Request sent"),
                                    ("REQUEST_APPROVED", "Request approved"),
                                    ("PAYMENT_MADE", "Payment made"),
                                    ("TOOL_PICKED_UP", "Tool picked up"),
                                    ("BOOKING_CANCELLED", "Booking cancelled"),
                                    ("BOOKING_COMPLETED", "Booking completed"),
                                ],
                                max_length=32,
                                null=True,
                            ),
                        ),
                        ("text", models.TextField(blank=True)),
                        (
                            "created_at",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        (
                            "conversation",
                            models.ForeignKey(
                                on_delete=models.CASCADE,
                                related_name="messages",
                                to="chat.conversation",
                            ),
                        ),
                        (
                            "sender",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=models.SET_NULL,
                                related_name="chat_messages",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["created_at"],
                        "db_table": "bookings_message",
                    },
                ),
            ],
        )
    ]
