# Generated by Django 5.2.4 on 2025-12-09 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_conversation_listing(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")

    conversations = (
        Conversation.objects.filter(booking__isnull=False, listing__isnull=True)
        .select_related("booking__listing")
    )
    for conv in conversations:
        booking = getattr(conv, "booking", None)
        listing = getattr(booking, "listing", None)
        if listing:
            conv.listing_id = listing.id
            conv.save(update_fields=["listing"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_booking_deposit_locked_booking_is_disputed"),
        ("chat", "0002_conversationreadstate"),
        ("listings", "0007_listing_deleted_at_listing_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                help_text="Listing this conversation is about (for pre-booking chat).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="listings.listing",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="bookings.booking",
            ),
        ),
        migrations.RunPython(populate_conversation_listing, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("booking__isnull", False), ("listing__isnull", False), _connector="OR"
                ),
                name="conversation_booking_or_listing_not_null",
            ),
        ),
    ]
