# Generated by Django 5.2.4 on 2025-12-02 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0008_booking_after_photos_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_by_role', models.CharField(choices=[('renter', 'renter'), ('owner', 'owner')], max_length=16)),
                ('damage_flow_kind', models.CharField(choices=[('generic', 'generic'), ('broke_during_use', 'broke_during_use')], default='generic', max_length=32)),
                ('category', models.CharField(choices=[('damage', 'damage'), ('missing_item', 'missing_item'), ('not_as_described', 'not_as_described'), ('late_return', 'late_return'), ('incorrect_charges', 'incorrect_charges'), ('safety_or_fraud', 'safety_or_fraud')], max_length=32)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('intake_missing_evidence', 'intake_missing_evidence'), ('awaiting_rebuttal', 'awaiting_rebuttal'), ('under_review', 'under_review'), ('resolved_renter', 'resolved_renter'), ('resolved_owner', 'resolved_owner'), ('resolved_partial', 'resolved_partial'), ('closed_auto', 'closed_auto')], default='open', max_length=32)),
                ('damage_assessment_category', models.CharField(blank=True, choices=[('A_internal', 'A_internal'), ('B_external', 'B_external'), ('C_safety', 'C_safety'), ('unknown', 'unknown')], max_length=16, null=True)),
                ('is_safety_incident', models.BooleanField(default=False)),
                ('requires_listing_suspend', models.BooleanField(default=False)),
                ('refund_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_capture_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rebuttal_due_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_locked', models.BooleanField(default=False, help_text='Mirror flag to block deposit auto-release while this dispute is active.')),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_cases', to='bookings.booking')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'photo'), ('video', 'video'), ('other', 'other')], max_length=16)),
                ('s3_key', models.CharField(max_length=512)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=64)),
                ('av_status', models.CharField(choices=[('pending', 'pending'), ('clean', 'clean'), ('infected', 'infected'), ('failed', 'failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.disputecase')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('renter', 'renter'), ('owner', 'owner'), ('admin', 'admin'), ('system', 'system')], max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.disputecase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['booking', 'status'], name='disputes_di_booking_9abad1_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['opened_by'], name='disputes_di_opened__1ef1a9_idx'),
        ),
    ]
