# Generated by Django 5.2.4 on 2025-12-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputecase',
            name='auto_rebuttal_timeout',
            field=models.BooleanField(default=False, help_text='True when the rebuttal window expired without a response.'),
        ),
    ]
