# Generated by Django 5.2.4 on 2025-12-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disputes", "0002_disputecase_auto_rebuttal_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputecase",
            name="intake_evidence_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disputecase",
            name="rebuttal_12h_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
