# Generated by Django 5.2.7 on 2025-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disputes", "0003_disputecase_intake_evidence_due_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disputecase",
            name="category",
            field=models.CharField(
                choices=[
                    ("damage", "damage"),
                    ("missing_item", "missing_item"),
                    ("not_as_described", "not_as_described"),
                    ("late_return", "late_return"),
                    ("incorrect_charges", "incorrect_charges"),
                    ("pickup_no_show", "pickup_no_show"),
                    ("safety_or_fraud", "safety_or_fraud"),
                ],
                max_length=32,
            ),
        ),
    ]
