# Generated by Django 5.2.7 on 2025-12-17 00:00

from django.db import migrations


def seed_operator_settings_defaults(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    DbSetting = apps.get_model("operator_settings", "DbSetting")
    FeatureFlag = apps.get_model("operator_settings", "FeatureFlag")
    MaintenanceBanner = apps.get_model("operator_settings", "MaintenanceBanner")

    db_setting_defaults = [
        ("DISPUTE_FILING_WINDOW_HOURS", 24, "int"),
        ("DISPUTE_REBUTTAL_WINDOW_HOURS", 24, "int"),
        ("DISPUTE_APPEAL_WINDOW_DAYS", 5, "int"),
        ("DISPUTE_ALLOW_LATE_SAFETY_FRAUD", True, "bool"),
    ]
    for key, value_json, value_type in db_setting_defaults:
        if DbSetting.objects.using(db_alias).filter(key=key).exists():
            continue
        DbSetting.objects.using(db_alias).create(
            key=key,
            value_json=value_json,
            value_type=value_type,
        )

    FeatureFlag.objects.using(db_alias).get_or_create(
        key="BOOKINGS_ENABLED",
        defaults={"enabled": True},
    )

    if not MaintenanceBanner.objects.using(db_alias).exists():
        MaintenanceBanner.objects.using(db_alias).create(
            enabled=False,
            severity="info",
            message="",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("operator_settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_operator_settings_defaults, migrations.RunPython.noop),
    ]

