# Generated by Django 5.2.7 on 2025-12-17 00:00

from django.db import migrations


def add_no_show_rebuttal_setting(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    DbSetting = apps.get_model("operator_settings", "DbSetting")
    key = "DISPUTE_NO_SHOW_REBUTTAL_HOURS"
    if DbSetting.objects.using(db_alias).filter(key=key).exists():
        return
    DbSetting.objects.using(db_alias).create(
        key=key,
        value_json=2,
        value_type="int",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("operator_settings", "0002_seed_defaults"),
    ]

    operations = [
        migrations.RunPython(add_no_show_rebuttal_setting, migrations.RunPython.noop),
    ]
