# Generated by Django 5.2.7 on 2025-11-21 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0006_listing_postal_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "price_cents",
                    models.PositiveIntegerField(help_text="Price charged for the plan, in cents."),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="How many days the promotion lasts."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PromotedSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("stripe_session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoted_slots",
                        to="listings.listing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoted_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="promotions.promotionplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-starts_at",),
                "indexes": [
                    models.Index(
                        fields=["listing", "active", "starts_at", "ends_at"],
                        name="promo_listing_active_dates_idx",
                    ),
                    models.Index(fields=["owner", "active"], name="promo_owner_active_idx"),
                ],
            },
        ),
    ]
