# Generated by Django 5.2.7 on 2025-11-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotedslot",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotedslot",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
