# Generated by Django 5.2.7 on 2025-11-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_alter_promotedslot_ends_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotedslot",
            name="plan",
        ),
        migrations.AddField(
            model_name="promotedslot",
            name="price_per_day_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="promotedslot",
            name="total_price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="PromotionPlan",
        ),
    ]
