# Generated by Django 5.2.4 on 2026-01-08 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_listingphoto_listings_li_listing_a0631b_idx"),
        ("promotions", "0004_add_promotion_breakdown_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="promotedslot",
            index=models.Index(
                fields=["active", "starts_at", "ends_at"], name="promo_active_window_idx"
            ),
        ),
    ]
