# Generated by Django 5.2.7 on 2025-12-13 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperatorAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("dispute_case", "Dispute Case"),
                            ("dispute_message", "Dispute Message"),
                            ("dispute_evidence", "Dispute Evidence"),
                        ],
                        max_length=64,
                    ),
                ),
                ("entity_id", models.CharField(max_length=64)),
                ("reason", models.TextField()),
                ("before_json", models.JSONField(blank=True, null=True)),
                ("after_json", models.JSONField(blank=True, null=True)),
                ("meta_json", models.JSONField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "created_at"],
                        name="operator_co_entity__5ba5e3_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="operator_co_actor_i_e9e367_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperatorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_notes_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="notes", to="operator_core.operatortag"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="operator_co_created_a6d01e_idx")
                ],
            },
        ),
    ]
