# Generated by Django 5.2.4 on 2025-12-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operator_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatorauditevent",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("listing", "Listing"),
                    ("booking", "Booking"),
                    ("dispute_case", "Dispute Case"),
                    ("dispute_message", "Dispute Message"),
                    ("dispute_evidence", "Dispute Evidence"),
                    ("operator_note", "Operator Note"),
                ],
                max_length=64,
            ),
        ),
    ]
