# Generated by Django 5.2.4 on 2025-12-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operator_core", "0002_alter_operatorauditevent_entity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_name", models.CharField(max_length=128)),
                ("params_json", models.JSONField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(choices=[("ok", "OK"), ("failed", "Failed")], max_length=16),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_name", "created_at"], name="operator_co_job_nam_89959b_idx"
                    )
                ],
            },
        ),
    ]
