# Generated by Django 5.2.7 on 2025-11-18 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0003_alter_booking_status"),
        ("listings", "0006_listing_postal_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=8
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking_charge", "Booking charge"),
                            ("damage_deposit_hold", "Damage deposit hold"),
                            ("damage_deposit_capture", "Damage deposit capture"),
                            ("damage_deposit_release", "Damage deposit release"),
                            ("owner_earning", "Owner earning"),
                            ("platform_fee", "Platform fee"),
                            ("promotion_purchase", "Promotion purchase"),
                            ("refund", "Refund"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount_cents", models.BigIntegerField()),
                ("currency", models.CharField(default="CAD", max_length=8)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("stripe_charge_id", models.CharField(blank=True, default="", max_length=120)),
                ("stripe_balance_txn_id", models.CharField(blank=True, default="", max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("effective_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bookings.booking",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="payments_tr_user_id_4ab1c7_idx"
                    ),
                    models.Index(fields=["booking"], name="payments_tr_booking_57109f_idx"),
                    models.Index(
                        fields=["stripe_balance_txn_id"], name="payments_tr_stripe__a32bad_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("stripe_balance_txn_id", ""), _negated=True),
                        fields=("user", "stripe_balance_txn_id"),
                        name="uniq_user_balance_txn",
                    )
                ],
            },
        ),
    ]
