# Generated by Django 5.2.7 on 2025-11-19 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BOOKING_CHARGE", "Booking charge"),
                            ("REFUND", "Refund"),
                            ("OWNER_EARNING", "Owner earning"),
                            ("PLATFORM_FEE", "Platform fee"),
                            ("DAMAGE_DEPOSIT_CAPTURE", "Damage deposit capture"),
                            ("DAMAGE_DEPOSIT_RELEASE", "Damage deposit release"),
                        ],
                        max_length=64,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="cad", max_length=8)),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True,
                        help_text="Related Stripe PaymentIntent / Charge / Refund id.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="transactions",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
