# Generated by Django 5.2.7 on 2025-11-20 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_transaction_simplification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerPayoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stripe_account_id", models.CharField(max_length=255)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("charges_enabled", models.BooleanField(default=False)),
                ("requirements_due", models.JSONField(blank=True, default=dict)),
                (
                    "is_fully_onboarded",
                    models.BooleanField(
                        default=False, help_text="Charges and payouts enabled, no disabled_reason."
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_synced_at", "user_id"],
            },
        ),
    ]
