# Generated by Django 5.2.4 on 2025-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerpayoutaccount",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="ownerpayoutaccount",
            name="institution_number",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="ownerpayoutaccount",
            name="transit_number",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
