# Generated by Django 5.2.4 on 2025-12-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_ownerpayoutaccount_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerpayoutaccount",
            name="lifetime_instant_payouts",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                help_text="Total gross amount ever sent via instant payouts.",
                max_digits=10,
            ),
        ),
    ]
