# Generated by Django 5.2.7 on 2026-01-02 00:00

from django.db import migrations, models


def migrate_owner_payouts(apps, schema_editor):
    Transaction = apps.get_model("payments", "Transaction")
    Transaction.objects.filter(
        kind="OWNER_EARNING",
        booking__isnull=True,
        promotion_slot__isnull=True,
        amount__lt=0,
    ).update(kind="OWNER_PAYOUT")


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_ownerpayoutaccount_lifetime_instant_payouts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("BOOKING_CHARGE", "Booking charge"),
                    ("REFUND", "Refund"),
                    ("OWNER_EARNING", "Owner earning"),
                    ("OWNER_PAYOUT", "Owner payout"),
                    ("PLATFORM_FEE", "Platform fee"),
                    ("DAMAGE_DEPOSIT_CAPTURE", "Damage deposit capture"),
                    ("DAMAGE_DEPOSIT_RELEASE", "Damage deposit release"),
                    ("PROMOTION_CHARGE", "Promotion charge"),
                ],
                max_length=64,
            ),
        ),
        migrations.RunPython(migrate_owner_payouts, migrations.RunPython.noop),
    ]
