# Generated by Django 5.2.7 on 2026-01-15 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_rename_payments_pa_user_id_7b8a32_idx_payments_pa_user_id_31b8c4_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerFeeTaxInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("fee_subtotal", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("gst", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("invoice_number", models.CharField(max_length=64, unique=True)),
                ("gst_number_snapshot", models.CharField(blank=True, default="", max_length=64)),
                ("pdf_s3_key", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owner_fee_invoices", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-period_start", "-created_at"],
                "unique_together": {("owner", "period_start", "period_end")},
            },
        ),
    ]
