name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: [staging, production]
        required: true
      image_sha:
        description: "API image SHA (defaults to current)"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - name: Resolve image tag
        id: img
        run: |
          if [ -z "${{ github.event.inputs.image_sha }}" ]; then
            echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
            echo "sha=${{ github.event.inputs.image_sha }}" >> $GITHUB_OUTPUT
          fi
      - name: Deploy (placeholder)
        run: |
          echo "Deploying ghcr.io/${{ github.repository }}/api:${{ steps.img.outputs.sha }} to ${{ github.event.inputs.env }}"
          # rsync compose files or call your infra tool here
