# Generated by Django 5.2.7 on 2025-11-10 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def set_photo_owner(apps, schema_editor):
    ListingPhoto = apps.get_model("listings", "ListingPhoto")
    for photo in ListingPhoto.objects.select_related("listing").all():
        listing = getattr(photo, "listing", None)
        if listing:
            photo.owner_id = listing.owner_id
            photo.save(update_fields=["owner"])


def unset_photo_owner(apps, schema_editor):
    ListingPhoto = apps.get_model("listings", "ListingPhoto")
    ListingPhoto.objects.update(owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listingphoto",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="filename",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="etag",
            field=models.CharField(blank=True, default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="av_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("clean", "Clean"),
                    ("infected", "Infected"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="listingphoto",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_photo_owner, unset_photo_owner),
        migrations.AlterField(
            model_name="listingphoto",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
