# Generated by Django 5.2.7 on 2025-11-10 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listingphoto_storage_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="daily_price_cad",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
