# Generated by Django 5.2.7 on 2025-11-13 21:21

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_daily_price_cad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Listing category",
                "verbose_name_plural": "Listing categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="damage_deposit_cad",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Damage deposit (CAD)",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Owner-controlled availability flag for rentals."
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="replacement_value_cad",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Replacement value (CAD)",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="daily_price_cad",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional category for this listing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listings.category",
            ),
        ),
    ]
