# Generated by Django 5.2.7 on 2025-11-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_category_listing_damage_deposit_cad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="accent",
            field=models.CharField(
                blank=True,
                help_text="CSS background color (e.g., Tailwind token or CSS variable).",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Lucide icon component name to render for this category.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon_color",
            field=models.CharField(
                blank=True,
                help_text="CSS color for the icon (e.g., Tailwind token or CSS variable).",
                max_length=80,
            ),
        ),
    ]
