# Generated by Django 5.2.7 on 2025-11-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_category_accent_category_icon_category_icon_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="postal_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional postal code to approximate the item's location.",
                max_length=12,
            ),
        ),
    ]
