# Generated by Django 5.2.4 on 2026-01-08 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_listing_deleted_at_listing_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listingphoto",
            index=models.Index(fields=["listing"], name="listings_li_listing_a0631b_idx"),
        ),
    ]
