# Generated by Django 5.2.4 on 2025-12-15 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_booking_deposit_authorization_fields"),
        ("operator_bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingevent",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS operator_bo_booking_e7cbaf_idx RENAME TO operator_bo_booking_171dcf_idx;",
            reverse_sql="ALTER INDEX IF EXISTS operator_bo_booking_171dcf_idx RENAME TO operator_bo_booking_e7cbaf_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS operator_bo_type_crea_7fa74e_idx RENAME TO operator_bo_type_7351de_idx;",
            reverse_sql="ALTER INDEX IF EXISTS operator_bo_type_7351de_idx RENAME TO operator_bo_type_crea_7fa74e_idx;",
        ),
        migrations.AlterField(
            model_name="bookingevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status change"),
                    ("email_sent", "Email sent"),
                    ("email_failed", "Email failed"),
                    ("sms_sent", "SMS sent"),
                    ("sms_failed", "SMS failed"),
                    ("operator_action", "Operator action"),
                    ("dispute_opened", "Dispute opened"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["-created_at", "-id"], name="operator_bo_created_f7f2df_idx"
            ),
        ),
    ]
