# Generated by Django 5.2.4
from django.conf import settings
from django.db import migrations


def rename_indexes_forward(apps, schema_editor):
    """
    Safety migration to rename legacy indexes if they still exist.
    Uses IF EXISTS to avoid failures when indexes were already renamed or never created.
    """
    if schema_editor.connection.vendor == "sqlite":
        return
    schema_editor.execute(
        "ALTER INDEX IF EXISTS operator_bo_booking_e7cbaf_idx "
        "RENAME TO operator_bo_booking_171dcf_idx;"
    )
    schema_editor.execute(
        "ALTER INDEX IF EXISTS operator_bo_type_crea_7fa74e_idx "
        "RENAME TO operator_bo_type_7351de_idx;"
    )


def rename_indexes_backward(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        return
    schema_editor.execute(
        "ALTER INDEX IF EXISTS operator_bo_booking_171dcf_idx "
        "RENAME TO operator_bo_booking_e7cbaf_idx;"
    )
    schema_editor.execute(
        "ALTER INDEX IF EXISTS operator_bo_type_7351de_idx "
        "RENAME TO operator_bo_type_crea_7fa74e_idx;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("operator_bookings", "0002_alter_bookingevent_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(rename_indexes_forward, rename_indexes_backward),
    ]
