# Generated by Django 5.2.4 on 2025-12-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operator_bookings", "0003_rename_operator_bo_booking_e7cbaf_idx_operator_bo_booking_171dcf_idx_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="bookingevent",
                    old_name="operator_bo_booking_e7cbaf_idx",
                    new_name="operator_bo_booking_171dcf_idx",
                ),
                migrations.RenameIndex(
                    model_name="bookingevent",
                    old_name="operator_bo_type_crea_7fa74e_idx",
                    new_name="operator_bo_type_7351de_idx",
                ),
            ],
        ),
    ]

