# Generated by Django 5.2.7 on 2026-01-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operator_bookings",
            "0004_rename_operator_bo_booking_e7cbaf_idx_operator_bo_booking_171dcf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status change"),
                    ("email_sent", "Email sent"),
                    ("email_failed", "Email failed"),
                    ("sms_sent", "SMS sent"),
                    ("sms_failed", "SMS failed"),
                    ("operator_action", "Operator action"),
                    ("dispute_opened", "Dispute opened"),
                    ("dispute_resolved", "Dispute resolved"),
                ],
                max_length=32,
            ),
        ),
    ]
