# Generated by Django 5.2.7 on 2025-11-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_loginevent_id_alter_passwordresetchallenge_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, default="", help_text="City for the primary address.", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Postal or ZIP code for the primary address.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Province or state for the primary address.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional street address for rentals.",
                max_length=255,
            ),
        ),
    ]
