# Generated by Django 5.2.7 on 2025-11-13 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_contactverificationchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_email_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_sms_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TwoFactorChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=8),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="Destination email or E.164 number.", max_length=255
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("consumed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["user", "channel"], name="tfc_user_channel_idx"),
                    models.Index(fields=["channel", "contact"], name="tfc_channel_contact_idx"),
                    models.Index(fields=["expires_at"], name="tfc_expires_idx"),
                ],
            },
        ),
    ]
