# Generated by Django 5.2.7 on 2025-11-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_two_factor_flags_twofactorchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile photo shown to other users.",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
