# Generated by Django 5.2.7 on 2025-11-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe Customer ID for renter payments.",
                max_length=120,
            ),
        ),
    ]
