# Generated by Django 5.2.7 on 2025-11-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
